# PostgreSQL. Versions 9.3 and up are supported.
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mysite_development
  username: postgres
  password: postgres
  host: localhost
  port: 5432

test:
  <<: *default
  database: mysite_test
  username: postgres
  password: postgres
  host: localhost
  port: 5432

production:
  <<: *default
  database: mysite_production
  username: mysite
  password: <%= ENV["MYSITE_DATABASE_PASSWORD"] %>
